server:
  port: "8050"
  cors:
    allowedOrigins: ["*"]
    allowedMethods: ["GET"]
    allowedHeaders: ["Content-Type"]
database:
  type: "sqlite"
  dsn: "shop.db"
admin:
  api_key: "your_api_key"
  api_hash: "your_api_hash"
  cors:
    allowedOrigins: ["*"]
    allowedMethods: ["GET", "POST", "PUT", "DELETE"]
    allowedHeaders: ["Content-Type", "API-KEY", "API-HASH"]
rabbitmq:
  url: "amqp://shoplist:T27t86S8v8d3WYIc3L3ktyDU31Clgjnh@100.84.176.50:5672/"
  queue: "shop_queue"